/* ============================================================
   LH.GL — the device.

   A thin WebGL2 wrapper: compile programs and introspect their
   uniforms once, upload interleaved meshes into VAOs, and keep a
   little redundant-state cache so a frame that draws 600 batches
   doesn't make 600 useless bind calls.

   Vertex layout is fixed at 11 floats — position, normal, uv,
   colour — because every mesh in this game is generated by the
   same builders and there is no importer to accommodate.
   ============================================================ */
(function(){
'use strict';
var M=LH.M;
var GL={};

/* Interleaved vertex: pos(3) nrm(3) uv(2) col(3) mat(4).
   `mat` is (layer, emissive, layer2, blend). Two layers and a weight,
   not one layer: a texture-array index cannot be interpolated across
   a triangle, because the values in between address unrelated
   materials. Sampling both and mixing is the only way a sand-to-grass
   boundary comes out as a boundary rather than a rainbow. */
var VSTRIDE=15, VBYTES=VSTRIDE*4;
/* per-instance: mat4(16) + tint(4) */
var ISTRIDE=20, IBYTES=ISTRIDE*4;
/* per-vertex skinning, in its own buffer: four bone indices then four
   weights. It lives apart from the interleaved vertex rather than in
   it because terrain, props and architecture are the overwhelming
   majority of the geometry in this game and none of them are skinned —
   widening the shared vertex by eight floats would cost far more than
   the bodies ever save. */
var SSTRIDE=8, SBYTES=SSTRIDE*4;
/* How many bones a skinned draw may address. The skeleton is 22; the
   headroom is for anything a future rig adds without a shader edit.
   GLES3 guarantees 256 vec4 of vertex uniform storage and this asks
   for 128 of them, so it fits with room to spare. */
var NBONES=32;
GL.VSTRIDE=VSTRIDE;GL.ISTRIDE=ISTRIDE;GL.SSTRIDE=SSTRIDE;GL.NBONES=NBONES;

var gl=null, canvas=null;
var _prog=null,_vao=null,_tex=[null,null,null,null];

GL.init=function(cv){
  canvas=cv;
  var opts={alpha:false,antialias:true,depth:true,stencil:false,
    powerPreference:'high-performance',preserveDrawingBuffer:false,
    premultipliedAlpha:false,desynchronized:false};
  gl=cv.getContext('webgl2',opts);
  if(!gl)return null;
  GL.gl=gl;
  /* Float colour buffers would be nicer for the bloom pass but are not
     universally filterable; half-float is, so ask for that extension and
     fall back to plain RGBA8 if it is missing. */
  GL.extHF=gl.getExtension('EXT_color_buffer_half_float');
  GL.extAF=gl.getExtension('EXT_texture_filter_anisotropic');
  GL.maxAniso=GL.extAF?gl.getParameter(GL.extAF.MAX_TEXTURE_MAX_ANISOTROPY_EXT):1;
  gl.enable(gl.DEPTH_TEST);
  gl.depthFunc(gl.LEQUAL);
  gl.enable(gl.CULL_FACE);
  gl.cullFace(gl.BACK);
  gl.frontFace(gl.CCW);
  gl.clearColor(0.03,0.04,0.07,1);
  return gl;
};

/* ---------------- programs ---------------- */
function compile(type,src,label){
  var s=gl.createShader(type);
  gl.shaderSource(s,src);
  gl.compileShader(s);
  if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){
    var log=gl.getShaderInfoLog(s)||'';
    /* Point at the offending line rather than dumping the whole shader:
       a 200-line shader in the console is unreadable. */
    var m=/ERROR:\s*\d+:(\d+)/.exec(log);
    var ctx='';
    if(m){
      var lines=src.split('\n'),ln=parseInt(m[1],10)-1;
      for(var i=Math.max(0,ln-2);i<Math.min(lines.length,ln+3);i++)
        ctx+='\n'+(i===ln?'>> ':'   ')+(i+1)+': '+lines[i];
    }
    gl.deleteShader(s);
    throw new Error('shader '+label+': '+log+ctx);
  }
  return s;
}

GL.program=function(name,vsrc,fsrc){
  var vs=compile(gl.VERTEX_SHADER,vsrc,name+'.vert');
  var fs=compile(gl.FRAGMENT_SHADER,fsrc,name+'.frag');
  var p=gl.createProgram();
  gl.attachShader(p,vs);gl.attachShader(p,fs);
  gl.linkProgram(p);
  if(!gl.getProgramParameter(p,gl.LINK_STATUS))
    throw new Error('link '+name+': '+gl.getProgramInfoLog(p));
  gl.deleteShader(vs);gl.deleteShader(fs);

  /* Introspect once at build time. Looking uniforms up by string in the
     draw loop is the classic way to make a JS renderer slow. */
  var uni={},n=gl.getProgramParameter(p,gl.ACTIVE_UNIFORMS);
  for(var i=0;i<n;i++){
    var info=gl.getActiveUniform(p,i);
    var key=info.name.replace(/\[0\]$/,'');
    uni[key]=gl.getUniformLocation(p,info.name);
  }
  var atr={},an=gl.getProgramParameter(p,gl.ACTIVE_ATTRIBUTES);
  for(var j=0;j<an;j++){
    var ai=gl.getActiveAttrib(p,j);
    atr[ai.name]=gl.getAttribLocation(p,ai.name);
  }
  return {name:name,p:p,u:uni,a:atr};
};

GL.use=function(prog){
  if(_prog===prog)return prog;
  _prog=prog;gl.useProgram(prog.p);return prog;
};

/* Uniform setters that no-op on absent names, so a shader variant can
   drop a uniform without every call site learning about it. */
GL.u1f=function(p,n,v){var l=p.u[n];if(l)gl.uniform1f(l,v);};
GL.u1i=function(p,n,v){var l=p.u[n];if(l!==undefined&&l!==null)gl.uniform1i(l,v);};
GL.u2f=function(p,n,a,b){var l=p.u[n];if(l)gl.uniform2f(l,a,b);};
GL.u3f=function(p,n,a,b,c){var l=p.u[n];if(l)gl.uniform3f(l,a,b,c);};
GL.u3v=function(p,n,v){var l=p.u[n];if(l)gl.uniform3f(l,v[0],v[1],v[2]);};
GL.u4f=function(p,n,a,b,c,d){var l=p.u[n];if(l)gl.uniform4f(l,a,b,c,d);};
GL.u4fv=function(p,n,v){var l=p.u[n];if(l)gl.uniform4fv(l,v);};
GL.uM4=function(p,n,m){var l=p.u[n];if(l)gl.uniformMatrix4fv(l,false,m);};
/* An array of mat4s, for the bone palette. Same call as uM4 — the
   distinction is only that the caller is passing NB*16 floats — but it
   is worth its own name so a reader of the draw loop can see that a
   palette is going up rather than one transform. */
GL.uBones=function(p,m){var l=p.u['uBones'];if(l)gl.uniformMatrix4fv(l,false,m);};
GL.uM3=function(p,n,m){var l=p.u[n];if(l)gl.uniformMatrix3fv(l,false,m);};

/* ---------------- meshes ---------------- */
/* A mesh owns a VAO. `data` is the interleaved Float32Array from
   LH.Geo, `idx` a Uint16/Uint32Array. Optionally instanced: pass
   maxInstances and the VAO gets divisor-1 attributes 5..9. */
GL.mesh=function(data,idx,maxInstances,skin){
  var vao=gl.createVertexArray();
  gl.bindVertexArray(vao);

  var vbo=gl.createBuffer();
  gl.bindBuffer(gl.ARRAY_BUFFER,vbo);
  gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);
  gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,VBYTES,0);
  gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,VBYTES,12);
  gl.enableVertexAttribArray(2);gl.vertexAttribPointer(2,2,gl.FLOAT,false,VBYTES,24);
  gl.enableVertexAttribArray(3);gl.vertexAttribPointer(3,3,gl.FLOAT,false,VBYTES,32);
  gl.enableVertexAttribArray(4);gl.vertexAttribPointer(4,4,gl.FLOAT,false,VBYTES,44);

  var ebo=gl.createBuffer();
  gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ebo);
  gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,idx,gl.STATIC_DRAW);

  var ibo=null,idata=null;
  if(maxInstances){
    ibo=gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER,ibo);
    idata=new Float32Array(maxInstances*ISTRIDE);
    gl.bufferData(gl.ARRAY_BUFFER,idata.byteLength,gl.DYNAMIC_DRAW);
    /* a mat4 attribute is four vec4 slots */
    for(var k=0;k<4;k++){
      var loc=5+k;
      gl.enableVertexAttribArray(loc);
      gl.vertexAttribPointer(loc,4,gl.FLOAT,false,IBYTES,k*16);
      gl.vertexAttribDivisor(loc,1);
    }
    gl.enableVertexAttribArray(9);
    gl.vertexAttribPointer(9,4,gl.FLOAT,false,IBYTES,64);
    gl.vertexAttribDivisor(9,1);
  }

  var sbo=null;
  if(skin){
    sbo=gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER,sbo);
    gl.bufferData(gl.ARRAY_BUFFER,skin,gl.STATIC_DRAW);
    gl.enableVertexAttribArray(10);
    gl.vertexAttribPointer(10,4,gl.FLOAT,false,SBYTES,0);
    gl.enableVertexAttribArray(11);
    gl.vertexAttribPointer(11,4,gl.FLOAT,false,SBYTES,16);
  }

  gl.bindVertexArray(null);
  return {
    vao:vao,vbo:vbo,ebo:ebo,ibo:ibo,sbo:sbo,skinned:!!skin,
    idata:idata,count:idx.length,
    itype:(idx instanceof Uint32Array)?gl.UNSIGNED_INT:gl.UNSIGNED_SHORT,
    instances:0,maxInstances:maxInstances||0,
    /* cached for frustum culling — filled by Geo builders */
    bmin:null,bmax:null,radius:0
  };
};

GL.updateInstances=function(mesh,count){
  if(!mesh.ibo)return;
  mesh.instances=count;
  if(!count)return;
  gl.bindBuffer(gl.ARRAY_BUFFER,mesh.ibo);
  gl.bufferSubData(gl.ARRAY_BUFFER,0,mesh.idata,0,count*ISTRIDE);
};

GL.bindMesh=function(mesh){
  if(_vao===mesh.vao)return;
  _vao=mesh.vao;gl.bindVertexArray(mesh.vao);
};

GL.draw=function(mesh){
  GL.bindMesh(mesh);
  gl.drawElements(gl.TRIANGLES,mesh.count,mesh.itype,0);
  GL.stats.draws++;GL.stats.tris+=mesh.count/3;
};

GL.drawInstanced=function(mesh,count){
  if(count===undefined)count=mesh.instances;
  if(!count)return;
  GL.bindMesh(mesh);
  gl.drawElementsInstanced(gl.TRIANGLES,mesh.count,mesh.itype,0,count);
  GL.stats.draws++;GL.stats.tris+=mesh.count/3*count;
};

GL.freeMesh=function(m){
  if(!m)return;
  gl.deleteVertexArray(m.vao);gl.deleteBuffer(m.vbo);gl.deleteBuffer(m.ebo);
  if(m.ibo)gl.deleteBuffer(m.ibo);
  if(_vao===m.vao)_vao=null;
};

/* ---------------- textures ---------------- */
GL.texFromCanvas=function(cv,opt){
  opt=opt||{};
  var t=gl.createTexture();
  gl.bindTexture(gl.TEXTURE_2D,t);
  gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,opt.flip!==false);
  /* sRGB unless the caller wants raw data (masks, lookup tables) */
  var ifmt=opt.linear?gl.RGBA:gl.SRGB8_ALPHA8;
  gl.texImage2D(gl.TEXTURE_2D,0,ifmt,gl.RGBA,gl.UNSIGNED_BYTE,cv);
  gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);
  var wrap=opt.clamp?gl.CLAMP_TO_EDGE:gl.REPEAT;
  gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,wrap);
  gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,wrap);
  if(opt.nearest){
    gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST_MIPMAP_LINEAR);
    gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);
  }else{
    gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);
    gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);
  }
  gl.generateMipmap(gl.TEXTURE_2D);
  if(GL.extAF&&GL.maxAniso>1)
    gl.texParameterf(gl.TEXTURE_2D,GL.extAF.TEXTURE_MAX_ANISOTROPY_EXT,
      Math.min(8,GL.maxAniso));
  gl.bindTexture(gl.TEXTURE_2D,null);
  return t;
};

/* A 2D array texture is how the world gets many surfaces in one draw:
   every block and terrain material is a layer, and the vertex colour's
   unused slot carries the layer index. */
GL.texArrayFromCanvases=function(list,size,opt){
  opt=opt||{};
  if(opt.data)return GL.dataArrayFromCanvases(list,size);
  var t=gl.createTexture();
  gl.bindTexture(gl.TEXTURE_2D_ARRAY,t);
  /* SRGB8_ALPHA8, not RGBA8. The canvases are painted in sRGB, and the
     lighting maths downstream is linear — asking the sampler to do the
     conversion is both free and the only way the two agree. With RGBA8
     every surface comes back roughly a stop and a half too bright and
     visibly desaturated. Alpha is never sRGB-encoded and passes through
     untouched, which is what the glass layer needs. */
  gl.texStorage3D(gl.TEXTURE_2D_ARRAY,
    Math.floor(Math.log2(size))+1,gl.SRGB8_ALPHA8,size,size,list.length);
  gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);
  for(var i=0;i<list.length;i++){
    gl.texSubImage3D(gl.TEXTURE_2D_ARRAY,0,0,0,i,size,size,1,
      gl.RGBA,gl.UNSIGNED_BYTE,list[i]);
  }
  gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);
  gl.generateMipmap(gl.TEXTURE_2D_ARRAY);
  gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);
  gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_MAG_FILTER,gl.LINEAR);
  gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_WRAP_S,gl.REPEAT);
  gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_WRAP_T,gl.REPEAT);
  if(GL.extAF&&GL.maxAniso>1)
    gl.texParameterf(gl.TEXTURE_2D_ARRAY,GL.extAF.TEXTURE_MAX_ANISOTROPY_EXT,
      Math.min(8,GL.maxAniso));
  gl.bindTexture(gl.TEXTURE_2D_ARRAY,null);
  return t;
};

/* The same upload without the sRGB decode. Normal and roughness maps
   are numbers, not colours: running them through a gamma curve bends
   every normal toward the surface and makes every rough surface look
   polished. */
GL.dataArrayFromCanvases=function(list,size){
  var t=gl.createTexture();
  gl.bindTexture(gl.TEXTURE_2D_ARRAY,t);
  gl.texStorage3D(gl.TEXTURE_2D_ARRAY,
    Math.floor(Math.log2(size))+1,gl.RGBA8,size,size,list.length);
  gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);
  for(var i=0;i<list.length;i++)
    gl.texSubImage3D(gl.TEXTURE_2D_ARRAY,0,0,0,i,size,size,1,
      gl.RGBA,gl.UNSIGNED_BYTE,list[i]);
  gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);
  gl.generateMipmap(gl.TEXTURE_2D_ARRAY);
  gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);
  gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_MAG_FILTER,gl.LINEAR);
  gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_WRAP_S,gl.REPEAT);
  gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_WRAP_T,gl.REPEAT);
  gl.bindTexture(gl.TEXTURE_2D_ARRAY,null);
  return t;
};

GL.bindTex=function(unit,tex,target){
  target=target||gl.TEXTURE_2D;
  if(_tex[unit]===tex)return;
  _tex[unit]=tex;
  gl.activeTexture(gl.TEXTURE0+unit);
  gl.bindTexture(target,tex);
};

/* ---------------- render targets ---------------- */
GL.shadowTarget=function(size){
  var fb=gl.createFramebuffer();
  var tex=gl.createTexture();
  gl.bindTexture(gl.TEXTURE_2D,tex);
  gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,size,size,0,
    gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);
  gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);
  gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);
  gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);
  gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
  /* Hardware comparison sampling gives free 2x2 PCF on the lookup, which
     is most of what makes the shadow edge acceptable at this resolution. */
  gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_COMPARE_MODE,gl.COMPARE_REF_TO_TEXTURE);
  gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_COMPARE_FUNC,gl.LEQUAL);
  gl.bindFramebuffer(gl.FRAMEBUFFER,fb);
  gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,tex,0);
  gl.drawBuffers([gl.NONE]);gl.readBuffer(gl.NONE);
  var ok=gl.checkFramebufferStatus(gl.FRAMEBUFFER)===gl.FRAMEBUFFER_COMPLETE;
  gl.bindFramebuffer(gl.FRAMEBUFFER,null);
  gl.bindTexture(gl.TEXTURE_2D,null);
  return {fb:fb,tex:tex,size:size,ok:ok};
};

GL.colorTarget=function(w,h,half,depthAsTexture){
  var fb=gl.createFramebuffer();
  var tex=gl.createTexture();
  var ifmt=(half&&GL.extHF)?gl.RGBA16F:gl.RGBA8;
  var type=(half&&GL.extHF)?gl.HALF_FLOAT:gl.UNSIGNED_BYTE;
  gl.bindTexture(gl.TEXTURE_2D,tex);
  gl.texImage2D(gl.TEXTURE_2D,0,ifmt,w,h,0,gl.RGBA,type,null);
  gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);
  gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);
  gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);
  gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
  gl.bindFramebuffer(gl.FRAMEBUFFER,fb);
  gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,tex,0);
  var depth=null,depthTex=null;
  if(depthAsTexture){
    /* A renderbuffer is cheaper but cannot be sampled, and the outline
       pass reads depth. Only the scene target pays for a texture. */
    depthTex=gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D,depthTex);
    gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,w,h,0,
      gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);
    gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
    gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,depthTex,0);
  }else if(half!=='nodepth'){
    depth=gl.createRenderbuffer();
    gl.bindRenderbuffer(gl.RENDERBUFFER,depth);
    gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT24,w,h);
    gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,depth);
  }
  var ok=gl.checkFramebufferStatus(gl.FRAMEBUFFER)===gl.FRAMEBUFFER_COMPLETE;
  gl.bindFramebuffer(gl.FRAMEBUFFER,null);
  return {fb:fb,tex:tex,depth:depth,depthTex:depthTex,w:w,h:h,ok:ok};
};

GL.resizeColorTarget=function(t,w,h,half){
  if(t.w===w&&t.h===h)return t;
  t.w=w;t.h=h;
  var ifmt=(half&&GL.extHF)?gl.RGBA16F:gl.RGBA8;
  var type=(half&&GL.extHF)?gl.HALF_FLOAT:gl.UNSIGNED_BYTE;
  gl.bindTexture(gl.TEXTURE_2D,t.tex);
  gl.texImage2D(gl.TEXTURE_2D,0,ifmt,w,h,0,gl.RGBA,type,null);
  if(t.depthTex){
    gl.bindTexture(gl.TEXTURE_2D,t.depthTex);
    gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,w,h,0,
      gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);
  }else if(t.depth){
    gl.bindRenderbuffer(gl.RENDERBUFFER,t.depth);
    gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT24,w,h);
  }
  gl.bindTexture(gl.TEXTURE_2D,null);
  return t;
};

GL.bindTarget=function(t){
  if(t){gl.bindFramebuffer(gl.FRAMEBUFFER,t.fb);gl.viewport(0,0,t.w||t.size,t.h||t.size);}
  else {gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,canvas.width,canvas.height);}
  _tex[0]=_tex[1]=_tex[2]=_tex[3]=null;
};

/* A VAO-less fullscreen triangle. gl_VertexID does the work, so there is
   nothing to bind and nothing to allocate. */
GL.fullscreen=function(){
  gl.bindVertexArray(GL._fsVAO||(GL._fsVAO=gl.createVertexArray()));
  _vao=GL._fsVAO;
  gl.drawArrays(gl.TRIANGLES,0,3);
  GL.stats.draws++;
};

GL.stats={draws:0,tris:0};
GL.resetStats=function(){GL.stats.draws=0;GL.stats.tris=0;};

LH.GL=GL;
})();

