#!/usr/bin/env python3
"""Assemble src/ into the shipped game, and the preview beside it.

    python3 tools/build.py            # build game/ and site/
    python3 tools/build.py --check    # build to memory and diff, touch nothing

The game is authored as one file per LH module under src/js, plus the CSS
sections and the HTML shell. It ships as one self-contained file because
that is what lets it run offline from a home screen with no install and no
round trip for code — the split is for people, not for the browser.
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, 'src')
GAME = os.path.join(ROOT, 'game', 'lumen-harbor.html')
PREV = os.path.join(ROOT, 'site', 'preview.html')


def assemble():
    order = json.load(open(os.path.join(SRC, 'manifest.json')))['order']
    out = []
    for path in order:
        full = os.path.join(SRC, path)
        if not os.path.exists(full):
            raise SystemExit('manifest names a missing file: ' + path)
        out.append(open(full, 'rb').read())
    return b''.join(out)


def preview(game):
    """The artifact build: same game, minus the bits a sandboxed iframe
    must not carry. Keep the whole head except these — dropping the rest
    of it once shipped a preview with no stylesheet at all."""
    src = game.decode('utf8')
    m = re.search(r'<head>(.*?)</head>', src, re.S)
    if not m:
        raise SystemExit('preview: no <head> in the built game')
    head = m.group(1)
    for pat in (r'\s*<meta\s+name="viewport"[^>]*>',
                r'\s*<meta\s+charset[^>]*>',
                r'\s*<link\s+rel="manifest"[^>]*>'):
        head = re.sub(pat, '', head)
    body = src[m.end():]
    body = re.sub(r'^\s*<body[^>]*>', '', body, flags=re.M)
    body = body.replace('</body>', '').replace('</html>', '')
    note = ('<!-- Generated by tools/build.py from game/lumen-harbor.html.\n'
            '     Do not edit this file: edit src/ and run the build. -->\n')
    out = note + head.strip('\n') + '\n' + body.rstrip() + '\n'

    problems = []
    if len(out) < len(game.decode('utf8')) * 0.97:
        problems.append('lost %.1f KB against the source'
                        % ((len(game.decode('utf8')) - len(out)) / 1024.0))
    for needle, what in (('#app{position:fixed', 'the layout CSS'),
                         ('#gl{position:absolute', 'the canvas CSS'),
                         ('LH.Device', 'the device layer'),
                         ('LH.Render', 'the renderer')):
        if needle not in out:
            problems.append('dropped ' + what)
    if problems:
        raise SystemExit('preview build is not sound: ' + '; '.join(problems))
    return out.encode('utf8')


def main():
    check = '--check' in sys.argv
    game = assemble()
    prev = preview(game)
    if check:
        old = open(GAME, 'rb').read()
        if old != game:
            print('MISMATCH: src/ does not reproduce game/lumen-harbor.html')
            print('  built %d bytes, on disk %d bytes' % (len(game), len(old)))
            for i in range(min(len(old), len(game))):
                if old[i] != game[i]:
                    print('  first difference at byte %d' % i)
                    print('  on disk: %r' % old[max(0, i - 40):i + 40])
                    print('  built  : %r' % game[max(0, i - 40):i + 40])
                    break
            return 1
        print('build --check: byte-identical (%d bytes, %d pieces)'
              % (len(game), len(json.load(open(os.path.join(SRC, 'manifest.json')))['order'])))
        return 0
    open(GAME, 'wb').write(game)
    open(PREV, 'wb').write(prev)
    print('game    %7d bytes  %s' % (len(game), os.path.relpath(GAME, ROOT)))
    print('preview %7d bytes  %s' % (len(prev), os.path.relpath(PREV, ROOT)))
    return 0


sys.exit(main())
