#!/usr/bin/env python3
"""Build site/preview.html — the artifact-hostable copy of the game.

The game ships as one document: doctype, head, meta, body. An Artifact
supplies its own skeleton and rejects a page that brings a second one,
so the preview is the same file with the outer document stripped and
nothing else changed. Running this after any change to the game keeps
the two in step; there is no second copy of the game to drift.

The viewport is not re-declared here — LH.Device asserts it at run
time, so the preview gets the game's own answer rather than the host's.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "game" / "lumen-harbor.html"
DST = ROOT / "site" / "preview.html"

src = SRC.read_text(encoding="utf-8")

head_open = src.index("<head>")
head_close = src.index("</head>")
head = src[head_open + len("<head>"):head_close]

# Keep only what an artifact cannot supply and that still works from the
# body: the title (the gallery reads it), and the font stylesheet.
keep = [
    line for line in head.splitlines()
    if line.strip().startswith("<title")
    or ("fonts.googleapis.com" in line or "fonts.gstatic.com" in line)
]

body_open = src.index("<body>") + len("<body>")
body_close = src.rindex("</body>")
body = src[body_open:body_close]

banner = (
    "<!-- Generated by tools/build-preview.py from game/lumen-harbor.html.\n"
    "     Do not edit this file: edit the game and run the script. -->\n"
)
out = banner + "\n".join(keep) + "\n" + body

DST.parent.mkdir(parents=True, exist_ok=True)
DST.write_text(out, encoding="utf-8")

for bad in ("<!doctype", "<html", "<head>", "<body>"):
    if bad in out.lower():
        sys.exit("preview still contains %s" % bad)

print("wrote %s (%.0f KB)" % (DST, len(out) / 1024))
