#!/usr/bin/env python3
"""Build site/preview.html — the artifact-hostable copy of the game.

The game ships as one document: doctype, head, meta, body. An Artifact
supplies its own skeleton and rejects a page that brings a second one,
so the preview is the same file with the outer document stripped and as
little else changed as possible. Running this after any change to the
game keeps the two in step; there is no second copy of the game.

What comes out of the head is *only* the viewport meta. Everything
else — the title, the font links, and above all the eleven hundred
lines of stylesheet — moves into the body, where browsers apply it
exactly as they would in the head.

That last point is the whole reason this script has a self-check at the
bottom. The first version of it kept a hand-picked list from the head:
the title and the font links. It dropped the stylesheet. The preview
booted perfectly — LH loaded, the world generated, the boot bar reached
"Ready" — and rendered as an unstyled 300x150 canvas at the top of a
thirty-thousand-pixel-tall page, because #app{position:fixed} was gone
along with everything else. Every boolean a test could have asserted
was true. So the checks below are about size and substance, not about
whether the thing loaded.

The viewport is dropped rather than rewritten because LH.Device asserts
its own at run time, and two viewport metas in one document is a
coin-toss over which one wins.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "game" / "lumen-harbor.html"
DST = ROOT / "site" / "preview.html"

src = SRC.read_text(encoding="utf-8")

head = src[src.index("<head>") + len("<head>"):src.index("</head>")]
# Drop the two things the artifact skeleton supplies itself, and the
# app-shell metas that mean nothing inside someone else's page.
head = re.sub(r'\s*<meta\s+name="viewport"[^>]*>', "", head)
head = re.sub(r'\s*<meta\s+charset[^>]*>', "", head)
head = re.sub(r'\s*<link\s+rel="manifest"[^>]*>', "", head)

body = src[src.index("<body>") + len("<body>"):src.rindex("</body>")]

out = (
    "<!-- Generated by tools/build-preview.py from game/lumen-harbor.html.\n"
    "     Do not edit this file: edit the game and run the script. -->\n"
    + head.strip() + "\n" + body
)

DST.parent.mkdir(parents=True, exist_ok=True)
DST.write_text(out, encoding="utf-8")

# ---- self-check ----------------------------------------------------
# Not "did it produce a file" but "is the game actually in it".
problems = []
for bad in ("<!doctype", "<html", "<head>", "<body>"):
    if bad in out.lower():
        problems.append("still contains %s" % bad)
# The Device layer *reads* meta[name="viewport"] by that exact string,
# so look for the tag rather than the substring.
if re.search(r'<meta\s+name="viewport"', out):
    problems.append("carries a second viewport meta")
if "<title>" not in out:
    problems.append("no <title>, so the artifact has no name")
# The stylesheet and the game are both enormous; anything much smaller
# than the source means a whole block went missing.
if len(out) < len(src) * 0.97:
    problems.append("lost %.1f KB against the source"
                    % ((len(src) - len(out)) / 1024))
for needle, what in (("#app{position:fixed", "the layout CSS"),
                     ("#gl{position:absolute", "the canvas CSS"),
                     ("LH.Device", "the device layer"),
                     ("LH.Render", "the renderer")):
    if needle not in out:
        problems.append("missing %s (%s)" % (what, needle))

if problems:
    sys.exit("preview build failed:\n  " + "\n  ".join(problems))

print("wrote %s (%.0f KB, source %.0f KB)"
      % (DST, len(out) / 1024, len(src) / 1024))
